### ISSUE TITLE
Implement read and write for glyph anchors

### ISSUE THREAD

**Issue by justvanrossum** [googlefonts/fontra-rcjk#174]
For testing purposes, you can add an `<anchor>` element to `tests/data/figArnaud.rcjk/characterGlyph/a.glif` as well as to `tests/data/figArnaud.rcjk/characterGlyph/bold/a.glif`

**Comment by justvanrossum** [comment]
Btw let's wait a bit with this issue: it is low priority, and has some edge-cases we will have to think about more.

**Comment by ollimeier** [comment]
OK
