### ISSUE TITLE
Username cookie is set in double quotes

### ISSUE THREAD

**Issue by nedkamburov** [googlefonts/fontra-rcjk#49]
In certain situations the username string is saved in double quotes.
This is probably caused by the inclusion of certain characters, such as @. The issue is reproducible on all browsers.

![Screenshot 2023-03-15 at 10 36 53](https://user-images.githubusercontent.com/11830669/225252867-93b2fb81-ca07-4cfd-9cc1-bfa097561e97.png)

**Comment by justvanrossum** [comment]
Some relevant issues on the aiohttp repo (this is the http server lib we use):
- https://github.com/aio-libs/aiohttp/issues/802
- https://github.com/aio-libs/aiohttp/issues/928

**Comment by justvanrossum** [comment]
So I think it's the server who does it, and we may have to remove the quotes in the browser.

**Comment by nedkamburov** [comment]
I am considering this idea https://stackoverflow.com/a/14582385 
I see 2 options: 
1. Deal with this on the front-end by just trimming the quotes
2. URL encode the cookie on the server side and decode it back on the front-end side

**Comment by nedkamburov** [comment]
Option 2 works well. I am not sure if I am not missing some potential issues though. Will commit a PR to continue the discussion.

**Comment by justvanrossum** [comment]
Yeah, let's try option 2.
